# Generated by Django 5.2.4 on 2025-07-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='decription',
            new_name='description',
        ),
    ]
